# Generated by Django 4.0.6 on 2022-08-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_alter_note_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.IntegerField(choices=[(0, 'Select'), (1, 'DRAFT'), (2, 'PUBLISH')], default=2, help_text='Select Either Draft or Publish'),
        ),
    ]
